services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

    environment:
      - SPRING_PROFILES_ACTIVE=docker

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword